- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Jenkins key
  shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -

- name: Add Jenkins repo
  copy:
    dest: /etc/apt/sources.list.d/jenkins.list
    content: "deb https://pkg.jenkins.io/debian-stable binary/"

- name: Install Jenkins
  apt:
    name: jenkins
    update_cache: yes

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true

# 🔥 Allow Jenkins to use kubectl
- name: Copy kubeconfig to Jenkins
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /var/lib/jenkins/.kube/config
    remote_src: yes
    owner: jenkins
    group: jenkins
    mode: '0644'
  ignore_errors: yes