- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Add Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: Create Jenkins .kube directory
  file:
    path: /var/lib/jenkins/.kube
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy k3s kubeconfig to Jenkins
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /var/lib/jenkins/.kube/config
    remote_src: yes
    owner: jenkins
    group: jenkins
    mode: '0644'
  ignore_errors: yes