- hosts: all
  become: true
  roles:
    - kubernetes
    - docker

- hosts: k8s_master
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - master
    - helm
    - monitoring
    - jenkins

- hosts: k8s_workers
  become: true
  roles:
    - worker