- name: Install Prometheus + Grafana
  shell: |
    helm install monitoring prometheus-community/kube-prometheus-stack \
    --namespace monitoring --create-namespace
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    creates: /home/ubuntu/.monitoring_installed

- name: Mark monitoring installed
  file:
    path: /home/ubuntu/.monitoring_installed
    state: touch