apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
spec:
  template:
    spec:
      containers:
        - name: db-seed
          image: postgres:12.4
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h postgres -U postgres; do
                echo "Waiting for postgres...";
                sleep 2;
              done;
              psql -h postgres -U postgres -d postgres \
              -c "CREATE TABLE IF NOT EXISTS votes (id VARCHAR(255) NOT NULL UNIQUE, vote VARCHAR(255) NOT NULL, created_at timestamp default NULL);"
          env:
            - name: PGPASSWORD
              value: "postgres"
      restartPolicy: Never