Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  (1..3).each do |i|
    config.vm.define "k8s-node-#{i}" do |node|
      node.vm.hostname = "k8s-node-#{i}"

      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end
end