# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-24.04"

#   (1..2).each do |i|
#     config.vm.define "k8s-node-#{i}" do |node|
#       node.vm.hostname = "k8s-node-#{i}"

#       node.vm.network "private_network", ip: "192.168.56.#{10 + i}"

#       node.vm.provider "virtualbox" do |vb|
#         vb.memory = 3072
#         vb.cpus = 3
#       end
#     end
#   end
# end


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  # --- VM 1 ---
  config.vm.define "k8s-node-1" do |node|
    node.vm.hostname = "k8s-node-1"

    node.vm.network "private_network", ip: "192.168.56.11"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
    end
  end

  # --- VM 2 ---
  # config.vm.define "k8s-node-2" do |node|
  #   node.vm.hostname = "k8s-node-2"

  #   node.vm.network "private_network", ip: "192.168.56.12"

  #   node.vm.provider "virtualbox" do |vb|
  #     vb.memory = 3072
  #     vb.cpus = 3
  #   end
  # end

end