- name: Install dependencies
  apt:
    name: ["apt-transport-https", "curl"]
    state: present

- name: Add Kubernetes repo
  shell: |
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

- name: Install kube tools
  apt:
    name: ["kubelet", "kubeadm", "kubectl"]
    state: present
    update_cache: yes

- name: Disable swap
  shell: swapoff -a