- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: '0644'

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes

- name: Update apt cache after adding Kubernetes repo
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    allow_downgrade: yes
    update_cache: yes
    mark: hold