- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes.list
    trusted: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    mark: hold

- name: Disable swap permanently
  replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: ''

- name: Disable swap immediately
  command: swapoff -a